# Copyright 2016 Casey Jaymes

# This file is part of PySCAP.
#
# PySCAP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PySCAP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PySCAP.  If not, see <http://www.gnu.org/licenses/>.
TAG_MAP = {
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}accesstoken_test': 'AccessTokenTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory57_test': 'ActiveDirectory57TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory_test': 'ActiveDirectoryTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicysubcategories_test': 'AuditEventPolicySubcategoriesTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicy_test': 'AuditEventPolicyTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}cmdlet_test': 'CmdletTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}dnscache_test': 'DnsCacheTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions53_test': 'FileAuditedPermissions53TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions_test': 'FileAuditedPermissionsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights53_test': 'FileEffectiveRights53TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights_test': 'FileEffectiveRightsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}file_test': 'FileTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_sid_test': 'GroupSidTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_test': 'GroupTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}interface_test': 'InterfaceTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}license_test': 'LicenseTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}lockoutpolicy_test': 'LockoutPolicyTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}metabase_test': 'MetabaseTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}ntuser_test': 'NtUserTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}passwordpolicy_test': 'PasswordPolicyTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}peheader_test': 'PeHeaderTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}port_test': 'PortTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}printereffectiverights_test': 'PrinterEffectiveRightsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process58_test': 'Process58TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process_test': 'ProcessTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}registry_test': 'RegistryTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions53_test': 'RegKeyAuditedPermissions53TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions_test': 'RegKeyAuditedPermissionsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights53_test': 'RegKeyEffectiveRights53TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights_test': 'RegKeyEffectiveRightsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}serviceeffectiverights_test': 'ServiceEffectiveRightsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}service_test': 'ServiceTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceauditedpermissions_test': 'SharedResourceAuditedPermissionsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceeffectiverights_test': 'SharedResourceEffectiveRightsTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresource_test': 'SharedResourceTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_sid_test': 'SidSidTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_test': 'SidTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}systemmetric_test': 'SystemMetricTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}uac_test': 'UacTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}userright_test': 'UserRightTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid55_test': 'UserSid55TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid_test': 'UserSidTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_test': 'UserTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}volume_test': 'VolumeTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi57_test': 'Wmi57TestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi_test': 'WmiTestElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wuaupdatesearcher_test': 'WuaUpdateSearcherTestElement',

    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}accesstoken_object': 'AccessTokenObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory57_object': 'ActiveDirectory57ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory_object': 'ActiveDirectoryObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicysubcategories_object': 'AuditEventPolicySubcategoriesObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicy_object': 'AuditEventPolicyObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}cmdlet_object': 'CmdletObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}dnscache_object': 'DnsCacheObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions53_object': 'FileAuditedPermissions53ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions_object': 'FileAuditedpermissionsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights53_object': 'FileEffectiveRights53ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights_object': 'FileEffectiveRightsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}file_object': 'FileObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_sid_object': 'GroupSidObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_object': 'GroupObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}interface_object': 'InterfaceObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}license_object': 'LicenseObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}lockoutpolicy_object': 'LockoutPolicyObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}metabase_object': 'MetabaseObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}ntuser_object': 'NtUserObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}passwordpolicy_object': 'PasswordPolicyObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}peheader_object': 'PeHeaderObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}port_object': 'PortObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}printereffectiverights_object': 'PrinterEffectiveRightsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process58_object': 'Process58ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process_object': 'ProcessObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}registry_object': 'RegistryObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions53_object': 'RegKeyAuditedPermissions53ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions_object': 'RegKeyAuditedPermissionsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights53_object': 'RegKeyEffectiveRights53ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights_object': 'RegKeyEffectiveRightsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}serviceeffectiverights_object': 'ServiceEffectiveRightsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}service_object': 'ServiceObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceauditedpermissions_object': 'SharedResourceAuditedPermissionsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceeffectiverights_object': 'SharedResourceEffectiveRightsObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresource_object': 'SharedResourceObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_sid_object': 'SidSidObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_object': 'SidObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}systemmetric_object': 'SystemMetricObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}uac_object': 'UacObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}userright_object': 'UserRightObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid55_object': 'UserSid55ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid_object': 'UserSidObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_object': 'UserObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}volume_object': 'VolumeObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi57_object': 'Wmi57ObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi_object': 'WmiObjectElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wuaupdatesearcher_object': 'WuaUpdateSearcherObjectElement',

    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}accesstoken_state': 'AccessTokenStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory57_state': 'ActiveDirectory57StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory_state': 'ActiveDirectoryStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicysubcategories_state': 'AuditEventPolicySubcategoriesStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicy_state': 'AuditEventPolicyStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}cmdlet_state': 'CmdletStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}dnscache_state': 'DnsCacheStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions53_state': 'FileAuditedPermissions53StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions_state': 'FileAuditedpermissionsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights53_state': 'FileEffectiveRights53StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights_state': 'FileEffectiveRightsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}file_state': 'FileStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_sid_state': 'GroupSidStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_state': 'GroupStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}interface_state': 'InterfaceStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}license_state': 'LicenseStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}lockoutpolicy_state': 'LockoutPolicyStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}metabase_state': 'MetabaseStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}ntuser_state': 'NtUserStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}passwordpolicy_state': 'PasswordPolicyStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}peheader_state': 'PeHeaderStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}port_state': 'PortStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}printereffectiverights_state': 'PrinterEffectiveRightsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process58_state': 'Process58StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process_state': 'ProcessStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}registry_state': 'RegistryStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions53_state': 'RegKeyAuditedPermissions53StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions_state': 'RegKeyAuditedPermissionsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights53_state': 'RegKeyEffectiveRights53StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights_state': 'RegKeyEffectiveRightsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}serviceeffectiverights_state': 'ServiceEffectiveRightsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}service_state': 'ServiceStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceauditedpermissions_state': 'SharedResourceAuditedPermissionsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceeffectiverights_state': 'SharedResourceEffectiveRightsStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresource_state': 'SharedResourceStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_sid_state': 'SidSidStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_state': 'SidStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}systemmetric_state': 'SystemMetricStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}uac_state': 'UacStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}userright_state': 'UserRightStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid55_state': 'UserSid55StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid_state': 'UserSidStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_state': 'UserStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}volume_state': 'VolumeStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi57_state': 'Wmi57StateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi_state': 'WmiStateElement',
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wuaupdatesearcher_state': 'WuaUpdateSearcherStateElement',
}

ADDR_TYPE_ENUMERATION = [
    'MIB_IPADDR_DELETED',
    'MIB_IPADDR_DISCONNECTED',
    'MIB_IPADDR_DYNAMIC',
    'MIB_IPADDR_PRIMARY',
    'MIB_IPADDR_TRANSIENT',
    '',
]

ADSTYPE_ENUMERATION = [
    'ADSTYPE_INVALID',
    'ADSTYPE_DN_STRING',
    'ADSTYPE_CASE_EXACT_STRING',
    'ADSTYPE_CASE_IGNORE_STRING',
    'ADSTYPE_PRINTABLE_STRING',
    'ADSTYPE_NUMERIC_STRING',
    'ADSTYPE_BOOLEAN',
    'ADSTYPE_INTEGER',
    'ADSTYPE_OCTET_STRING',
    'ADSTYPE_UTC_TIME',
    'ADSTYPE_LARGE_INTEGER',
    'ADSTYPE_PROV_SPECIFIC',
    'ADSTYPE_OBJECT_CLASS',
    'ADSTYPE_CASEIGNORE_LIST',
    'ADSTYPE_OCTET_LIST',
    'ADSTYPE_PATH',
    'ADSTYPE_POSTALADDRESS',
    'ADSTYPE_TIMESTAMP',
    'ADSTYPE_BACKLINK',
    'ADSTYPE_TYPEDNAME',
    'ADSTYPE_HOLD',
    'ADSTYPE_NETADDRESS',
    'ADSTYPE_REPLICAPOINTER',
    'ADSTYPE_FAXNUMBER',
    'ADSTYPE_EMAIL',
    'ADSTYPE_NT_SECURITY_DESCRIPTOR',
    'ADSTYPE_UNKNOWN',
    'ADSTYPE_DN_WITH_BINARY',
    'ADSTYPE_DN_WITH_STRING',
    '',
]

AUDIT_ENUMERATION = [
    'AUDIT_FAILURE',
    'AUDIT_NONE',
    'AUDIT_SUCCESS',
    'AUDIT_SUCCESS_FAILURE',
    '',
]

CMDLET_VERB_ENUMERATION = [
    'Approve',
    'Assert',
    'Compare',
    'Confirm',
    'Find',
    'Get',
    'Measure',
    'Read',
    'Request',
    'Resolve',
    'Search',
    'Select',
    'Show',
    'Test',
    'Trace',
    'Watch',
    '',
]

DRIVE_TYPE_ENUMERATION = [
    'DRIVE_UNKNOWN',
    'DRIVE_NO_ROOT_DIR',
    'DRIVE_REMOVABLE',
    'DRIVE_FIXED',
    'DRIVE_REMOTE',
    'DRIVE_CDROM',
    'DRIVE_RAMDISK',
    '',
]

FILE_TYPE_ENUMERATION = [
    'FILE_ATTRIBUTE_DIRECTORY',
    'FILE_TYPE_CHAR',
    'FILE_TYPE_DISK',
    'FILE_TYPE_PIPE',
    'FILE_TYPE_REMOTE',
    'FILE_TYPE_UNKNOWN',
    '',
]

INTERFACE_TYPE_ENUMERATION = [
    'MIB_IF_TYPE_ETHERNET',
    'MIB_IF_TYPE_FDDI',
    'MIB_IF_TYPE_LOOPBACK',
    'MIB_IF_TYPE_OTHER',
    'MIB_IF_TYPE_PPP',
    'MIB_IF_TYPE_SLIP',
    'MIB_IF_TYPE_TOKENRING',
    '',
]

NAMING_CONTEXT_ENUMERATION = [
    'domain',
    'configuration',
    'schema',
    '',
]

NTUSER_ACCOUNT_TYPE_ENUMERATION = [
    'local',
    'domain',
    '',
]

PE_SUBSYSTEM_ENUMERATION = [
    'IMAGE_SUBSYSTEM_UNKNOWN',
    'IMAGE_SUBSYSTEM_NATIVE',
    'IMAGE_SUBSYSTEM_WINDOWS_GUI',
    'IMAGE_SUBSYSTEM_WINDOWS_CUI',
    'IMAGE_SUBSYSTEM_OS2_CUI',
    'IMAGE_SUBSYSTEM_POSIX_CUI',
    'IMAGE_SUBSYSTEM_WINDOWS_CE_GUI',
    'IMAGE_SUBSYSTEM_EFI_APPLICATION',
    'IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER',
    'IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER',
    'IMAGE_SUBSYSTEM_EFI_ROM',
    'IMAGE_SUBSYSTEM_XBOX',
    'IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION',
    '',
]

PE_TARGET_MACHINE_ENUMERATION = [
    'IMAGE_FILE_MACHINE_UNKNOWN',
    'IMAGE_FILE_MACHINE_ALPHA',
    'IMAGE_FILE_MACHINE_ARM',
    'IMAGE_FILE_MACHINE_ALPHA64',
    'IMAGE_FILE_MACHINE_I386',
    'IMAGE_FILE_MACHINE_IA64',
    'IMAGE_FILE_MACHINE_M68K',
    'IMAGE_FILE_MACHINE_MIPS16',
    'IMAGE_FILE_MACHINE_MIPSFPU',
    'IMAGE_FILE_MACHINE_MIPSFPU16',
    'IMAGE_FILE_MACHINE_POWERPC',
    'IMAGE_FILE_MACHINE_R3000',
    'IMAGE_FILE_MACHINE_R4000',
    'IMAGE_FILE_MACHINE_R10000',
    'IMAGE_FILE_MACHINE_SH3',
    'IMAGE_FILE_MACHINE_SH4',
    'IMAGE_FILE_MACHINE_THUMB',
    '',
]

PROTOCOL_ENUMERATION = [
    'TCP',
    'UDP',
    '',
]

REGISTRY_HIVE_ENUMERATION = [
    'HKEY_CLASSES_ROOT',
    'HKEY_CURRENT_CONFIG',
    'HKEY_CURRENT_USER',
    'HKEY_LOCAL_MACHINE',
    'HKEY_USERS',
    '',
]

REGISTRY_TYPE_ENUMERATION = [
    'reg_binary',
    'reg_dword',
    'reg_dword_little_endian',
    'reg_dword_big_endian',
    'reg_expand_sz',
    'reg_link',
    'reg_multi_sz',
    'reg_none',
    'reg_qword',
    'reg_qword_little_endian',
    'reg_sz',
    'reg_resource_list',
    'reg_full_resource_descriptor',
    'reg_resource_requirements_list',
    '',
]

SERVICE_CONTROLS_ACCEPTED_ENUMERATION = [
    'SERVICE_ACCEPT_NETBINDCHANGE',
    'SERVICE_ACCEPT_PARAMCHANGE',
    'SERVICE_ACCEPT_PAUSE_CONTINUE',
    'SERVICE_ACCEPT_PRESHUTDOWN',
    'SERVICE_ACCEPT_SHUTDOWN',
    'SERVICE_ACCEPT_STOP',
    'SERVICE_ACCEPT_HARDWAREPROFILECHANGE',
    'SERVICE_ACCEPT_POWEREVENT',
    'SERVICE_ACCEPT_SESSIONCHANGE',
    'SERVICE_ACCEPT_TIMECHANGE',
    'SERVICE_ACCEPT_TRIGGEREVENT',
    '',
]

SERVICE_CURRENT_STATE_ENUMERATION = [
    'SERVICE_CONTINUE_PENDING',
    'SERVICE_PAUSE_PENDING',
    'SERVICE_PAUSED',
    'SERVICE_RUNNING',
    'SERVICE_START_PENDING',
    'SERVICE_STOP_PENDING',
    'SERVICE_STOPPED',
    '',
]

SERVICE_STATE_TYPE_ENUMERATION = [
    'SERVICE_AUTO_START',
    'SERVICE_BOOT_START',
    'SERVICE_DEMAND_START',
    'SERVICE_DISABLED',
    'SERVICE_SYSTEM_START',
    '',
]

SERVICE_TYPE_ENUMERATION = [
    'SERVICE_FILE_SYSTEM_DRIVER',
    'SERVICE_KERNEL_DRIVER',
    'SERVICE_WIN32_OWN_PROCESS',
    'SERVICE_WIN32_SHARE_PROCESS',
    'SERVICE_INTERACTIVE_PROCESS',
    '',
]

SHARED_RESOURCE_TYPE_ENUMERATION = [
    'STYPE_DISKTREE',
    'STYPE_DISKTREE_SPECIAL',
    'STYPE_DISKTREE_TEMPORARY',
    'STYPE_DISKTREE_SPECIAL_TEMPORARY',
    'STYPE_PRINTQ',
    'STYPE_PRINTQ_SPECIAL',
    'STYPE_PRINTQ_TEMPORARY',
    'STYPE_PRINTQ_SPECIAL_TEMPORARY',
    'STYPE_DEVICE',
    'STYPE_DEVICE_SPECIAL',
    'STYPE_DEVICE_TEMPORARY',
    'STYPE_DEVICE_SPECIAL_TEMPORARY',
    'STYPE_IPC',
    'STYPE_IPC_SPECIAL',
    'STYPE_IPC_TEMPORARY',
    'STYPE_IPC_SPECIAL_TEMPORARY',
    'STYPE_SPECIAL',
    'STYPE_TEMPORARY',
    '',
]

SYSTEM_METRIC_INDEX_ENUMERATION = [
    'SM_ARRANGE',
    'SM_CLEANBOOT',
    'SM_CMONITORS',
    'SM_CMOUSEBUTTONS',
    'SM_CXBORDER',
    'SM_CXCURSOR',
    'SM_CXDLGFRAME',
    'SM_CXDOUBLECLK',
    'SM_CXDRAG',
    'SM_CXEDGE',
    'SM_CXFIXEDFRAME',
    'SM_CXFOCUSBORDER',
    'SM_CXFRAME',
    'SM_CXFULLSCREEN',
    'SM_CXHSCROLL',
    'SM_CXHTHUMB',
    'SM_CXICON',
    'SM_CXICONSPACING',
    'SM_CXMAXIMIZED',
    'SM_CXMAXTRACK',
    'SM_CXMENUCHECK',
    'SM_CXMENUSIZE',
    'SM_CXMIN',
    'SM_CXMINIMIZED',
    'SM_CXMINSPACING',
    'SM_CXMINTRACK',
    'SM_CXPADDEDBORDER',
    'SM_CXSCREEN',
    'SM_CXSIZE',
    'SM_CXSIZEFRAME',
    'SM_CXSMICON',
    'SM_CXSMSIZE',
    'SM_CXVIRTUALSCREEN',
    'SM_CXVSCROLL',
    'SM_CYBORDER',
    'SM_CYCAPTION',
    'SM_CYCURSOR',
    'SM_CYDLGFRAME',
    'SM_CYDOUBLECLK',
    'SM_CYDRAG',
    'SM_CYEDGE',
    'SM_CYFIXEDFRAME',
    'SM_CYFOCUSBORDER',
    'SM_CYFRAME',
    'SM_CYFULLSCREEN',
    'SM_CYHSCROLL',
    'SM_CYICON',
    'SM_CYICONSPACING',
    'SM_CYKANJIWINDOW',
    'SM_CYMAXIMIZED',
    'SM_CYMAXTRACK',
    'SM_CYMENU',
    'SM_CYMENUCHECK',
    'SM_CYMENUSIZE',
    'SM_CYMIN',
    'SM_CYMINIMIZED',
    'SM_CYMINSPACING',
    'SM_CYMINTRACK',
    'SM_CYSCREEN',
    'SM_CYSIZE',
    'SM_CYSIZEFRAME',
    'SM_CYSMCAPTION',
    'SM_CYSMICON',
    'SM_CYSMSIZE',
    'SM_CYVIRTUALSCREEN',
    'SM_CYVSCROLL',
    'SM_CYVTHUMB',
    'SM_DBCSENABLED',
    'SM_DEBUG',
    'SM_DIGITIZER',
    'SM_IMMENABLED',
    'SM_MAXIMUMTOUCHES',
    'SM_MEDIACENTER',
    'SM_MENUDROPALIGNMENT',
    'SM_MIDEASTENABLED',
    'SM_MOUSEPRESENT',
    'SM_MOUSEHORIZONTALWHEELPRESENT',
    'SM_MOUSEWHEELPRESENT',
    'SM_NETWORK',
    'SM_PENWINDOWS',
    'SM_REMOTECONTROL',
    'SM_REMOTESESSION',
    'SM_SAMEDISPLAYFORMAT',
    'SM_SECURE',
    'SM_SERVERR2',
    'SM_SHOWSOUNDS',
    'SM_SHUTTINGDOWN',
    'SM_SLOWMACHINE',
    'SM_STARTER',
    'SM_SWAPBUTTON',
    'SM_TABLETPC',
    'SM_XVIRTUALSCREEN',
    'SM_YVIRTUALSCREEN',
    '',
]

USER_RIGHT_ENUMERATION = [
    'SE_ASSIGNPRIMARYTOKEN_NAME',
    'SE_AUDIT_NAME',
    'SE_BACKUP_NAME',
    'SE_CHANGE_NOTIFY_NAME',
    'SE_CREATE_GLOBAL_NAME',
    'SE_CREATE_PAGEFILE_NAME',
    'SE_CREATE_PERMANENT_NAME',
    'SE_CREATE_SYMBOLIC_LINK_NAME',
    'SE_CREATE_TOKEN_NAME',
    'SE_DEBUG_NAME',
    'SE_ENABLE_DELEGATION_NAME',
    'SE_IMPERSONATE_NAME',
    'SE_INC_BASE_PRIORITY_NAME',
    'SE_INCREASE_QUOTA_NAME',
    'SE_INC_WORKING_SET_NAME',
    'SE_LOAD_DRIVER_NAME',
    'SE_LOCK_MEMORY_NAME',
    'SE_MACHINE_ACCOUNT_NAME',
    'SE_MANAGE_VOLUME_NAME',
    'SE_PROF_SINGLE_PROCESS_NAME',
    'SE_RELABEL_NAME',
    'SE_REMOTE_SHUTDOWN_NAME',
    'SE_RESTORE_NAME',
    'SE_SECURITY_NAME',
    'SE_SHUTDOWN_NAME',
    'SE_SYNC_AGENT_NAME',
    'SE_SYSTEM_ENVIRONMENT_NAME',
    'SE_SYSTEM_PROFILE_NAME',
    'SE_SYSTEMTIME_NAME',
    'SE_TAKE_OWNERSHIP_NAME',
    'SE_TCB_NAME',
    'SE_TIME_ZONE_NAME',
    'SE_TRUSTED_CREDMAN_ACCESS_NAME',
    'SE_UNDOCK_NAME',
    'SE_UNSOLICITED_INPUT_NAME',
    'SE_BATCH_LOGON_NAME',
    'SE_DENY_BATCH_LOGON_NAME',
    'SE_DENY_INTERACTIVE_LOGON_NAME',
    'SE_DENY_NETWORK_LOGON_NAME',
    'SE_DENY_REMOTE_INTERACTIVE_LOGON_NAME',
    'SE_DENY_SERVICE_LOGON_NAME',
    'SE_INTERACTIVE_LOGON_NAME',
    'SE_NETWORK_LOGON_NAME',
    'SE_REMOTE_INTERACTIVE_LOGON_NAME',
    'SE_SERVICE_LOGON_NAME',
    '',
]

WINDOWS_VIEW_ENUMERATION = [
    '32_bit',
    '64_bit',
    '',
]
